name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to ACR
        run: |
          echo "${{ secrets.AZURE_REGISTRY_KEY }}" | docker login "registrybluejay.azurecr.io" --username "registrybluejay" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "IMAGE_TAG: ${IMAGE_TAG}"  # 태그 확인
          docker build -t registrybluejay.azurecr.io/myapp:latest .
          docker tag registrybluejay.azurecr.io/myapp:latest registrybluejay.azurecr.io/myapp:${IMAGE_TAG}

      - name: Push Docker image
        run: |
          docker push registrybluejay.azurecr.io/myapp:latest
          docker push registrybluejay.azurecr.io/myapp:${IMAGE_TAG}
